### ISSUE TITLE
Create user stories to clarify what app will do

### ISSUE THREAD

**Issue by brianrip** [brianrip/community_points#1]

**Comment by scottfirestone** [comment]
As an admin..
when it visits the root path…
and fills in username and password,
and clicks in logs in…
it is directed to admin/user page.
————
As a logged-in admin…
when it visits the user index page,
and clicks create new user,
and fills in username and password,
and clicks create user,
then it should see the users index,
with the newly created username and password as row.
<<repeat for update and delete>>
————
As a logged-in admin..
when it visits the activities index,
and clicks create new activity,
and fills in the activity name and point values,
and clicks create new activity,
then it should see the activities index,
with the newly created activity name and point value.
<<repeat for update and delete>>
———
As a logged-in admin..
when it visits the rewards index,
and clicks create new reward,
and fills in the reward name, point redemption cost, description, and upload photo,
and clicks create new reward,
then it should see the rewards index,
with the newly created reward name, point redemption cost, description, phˆoto.
<<repeat for update and delete>>
————
As an unlogged-in user,
when it visits the root path,
and fills in username and password,
and clicks log in,
it sees the users show page,
with username, completed activities, unused point total, used point total, and rewards redeemed.
————
As a logged-in user,
when it visits its show page,
and clicks dropdown to see activity,
they see a list of activities to mark complete,
and they select an activity to mark complete,
and they click submit completed activity,
then they see their user page with newly complete activity listed with points, and new point total.
—————
As a logged-in user with points,
when it visits the show page,
and clicks redeem reward,
then it sees the rewards index,
and it clicks the respective reward’s ‘redeem’ link,
then the user sees their show page,
with the picture of the newly redeemed reward,
and adjusted available points and redeemed points.
———————
